### ISSUE TITLE
`date` command in episode 5

### ISSUE THREAD

**Issue by ha0ye** [LibraryCarpentry/lc-shell#109] opened 2019-12-10 14:31 UTC
per @aadoek

The unix `date` command takes different options on Mac OS (because Mac uses BSD command line utilities rather than GNU). For this reason some of the examples that use `date -I` (to return the system date in ISO-8601 format) don't work.

A suggested fix is to specify the full date format for Mac:
`date +%Y-%m-%d` instead.

**Comment by mharp** [comment] 2020-01-08 23:22
This is indeed and issue (experienced in macOS Catalina) suggest including a notation our callout for Mac users.

**Comment by alex-ball** [comment] 2020-02-11 17:51
Duplicate of #85.

**Closed** 2020-06-20 17:45 UTC
Labels: status:duplicate
