### ISSUE TITLE
Mismatch between file name in Episode 5 (Counting and Mining) and Shell-lesson zip data files

### ISSUE THREAD

**Issue by emcaulay** [LibraryCarpentry/lc-shell#177] opened 2021-11-06 16:02 UTC
Hi all,

I'm passing on a comment that was passed on to me, but I did verify the problem reported on my own. An instructor reported it to @ErinBecker and she shared it with me. 

In Episode 5, on line 67 and 77 there is direct reference to a file named `2014-01_JA.tsv`, but when I download the zip file that is supposed to be the source for this file for the shell-lesson (available here in the "prerequisites" box: https://librarycarpentry.org/lc-shell/ in) it is not in the zip file. Nor is it in the current repo in the data subdirectory (https://github.com/LibraryCarpentry/lc-shell/tree/gh-pages/data). 

The file that is missing is integral to the whole episode, so it's important to have the correct filename in the lesson. I can't tell if the lesson is wrong and the correct file is in the zip folder (just under a different name) or whether we've lost the correct file over time and need to find it again. 

Thanks in advance for your help to get this corrected to support instructors.

**Comment by chendaniely** [comment] 2021-11-08 18:13
I looked through some of the history. it looks like this version of the zip file has the missing `2014-01_JA.tsv` file from this commit: https://github.com/LibraryCarpentry/lc-shell/commit/dffc00a37dbb062d9bccb3dfbf492488f25ae727


https://github.com/LibraryCarpentry/lc-shell/blob/d1334d832c6f1c745901535d52465ee4b57945b0/data/shell-lesson.zip


I haven't actually tested it with the lesson materials, but can someone confirm that that is the correct dataset? I was only looking for filename matches.

Also: I'm replying to this issue instead of #178 since this one came first.
Might help to rename the title and/or close #178 so the conversation stays together in a single issue.

**Comment by ErinBecker** [comment] 2021-11-09 03:39
Thanks for getting this issue in @emcaulay and sorry for forgetting which lesson you maintain! 😆 

I'm happy to put in a PR to add the missing file (thank you @chendaniely for finding it!). Assigning to myself.

**Comment by ErinBecker** [comment] 2021-11-09 15:33
The problem is actually bigger than I thought! 

1) There are multiple files missing from the zip file: 
* 2014-01_JA.tsv
* pg514.txt
* 201403160_01_text.json
* diary.html
Each of these files is used in the lesson and needs to be included in the zip file. All but `2014-01_JA.tsv` are included as individual files in the /data/ directory. 

2) When I attempt to add the missing files to the zip file and push up to GitHub, I get a file size error. 

>> remote: error: Trace: 5fd4d7027cfbe7fa19cae7c94202ae5dc0da83584a976463cda62a3f42511693
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File data/2014-01_JA.tsv is 125.05 MB; this exceeds GitHub's file size limit of 100.00 MB
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
To https://github.com/ErinBecker/lc-shell.git
 ! [remote rejected] gh-pages -> gh-pages (pre-receive hook declined)
error: failed to push some refs to 'https://github.com/ErinBecker/lc-shell.git'
(base) ebecker@Erins-MacBook-Air-2 data % 

Need to look into this more closely and figure out a work around for large file upload.

**Comment by kaitlinnewson** [comment] 2021-11-09 17:20
@ErinBecker in the live version, the only file I see missing when I download the zip is `2014-01_JA.tsv`. It may work if you zip the large tsv file first, then add it into the new zip.

**Comment by kaitlinnewson** [comment] 2021-11-09 17:29
I saw this shared in the Slack thread as well - it looks like it was previously zipped to get around the file size issue: https://github.com/LibraryCarpentry/lc-shell/tree/896c23489adaefebeaf316e75686f6a69f79fc81/data

**Comment by ErinBecker** [comment] 2021-11-10 14:28
Thank you @kaitlinnewson! I'll give this a try today.

**Comment by chendaniely** [comment] 2021-11-10 19:32
The R [piggyback](https://github.com/ropensci/piggyback) package allows you to leverage Github Releases to upload and work with large files.
If the underlying zipfile isn't going to be changed too much. we can think about using the releases to store zipfiles for the lessons moving forward.

**Closed** 2021-11-16 18:12 UTC
